### ISSUE TITLE
Cover Image hinzufügen

### ISSUE THREAD

**Issue by holema** [thomaspeissl/v-shopware-api-client#2]
Hallo @treffner 
hast du mit diesem Query ein Coverbild hinzufügen können?
Bei mir läuft der Patch zwar durch, aber das Bild wir nicht als Cover Image gesetzt.

https://github.com/treffner/v-shopware-api-client/blob/d28aa7805cfdf5c5d3505ef6ad7ecc30c57993cc/media.v#L99

So sieht das ganze in Python aus :)
```
    lUrl = api_path + '/product/'+productid
    data_cover = json.dumps({'coverId': product_media_id})
 
    conn.request("PATCH", lUrl, data_cover, headers)
```

**Comment by 7underlines** [comment]
Yes, you need to supply the product-media id here. Not the normal mediaId.

**Comment by 7underlines** [comment]
I recommend you join the shopware slack channel to get answers related to the api and not this module more quickly (currently about 3.6k members in the shopware6 channel) - https://www.shopware.com/en/news/an-introduction-to-the-shopware-community-slack/
